
name: Intergration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  run-intergraion-tests:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go mod download 
      - run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
      - run: ginkgo -v test/...
